name: Basic check of main.py

on:
  push:
    paths:
      - 'main.py'

jobs:
  check_main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.10'  # Use the version of Python you need

    - name: Set PyPI token
      run: poetry config pypi-token.pypi <valid_token_value>

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run main.py with input
      run: |
        echo -e "\n\n\nn" | python main.py
