name: Basic check of main.py

on:
  push:
    paths:
      - 'main.py'

jobs:
  check_main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.10'
        env:
          POETRY_PYPI_TOKEN: ${{secrets.PYPI_TOKEN}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Run main.py with input
      run: |
        echo -e "\n\n\nn" | poetry config pypi-token.pypi ${{secrets.PYPI_TOKEN}}
