name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Set PyPI token
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      if: secrets.PYPI_TOKEN != ''
    - name: Install dependencies
      run: poetry install
    - name: Test with pytest
      run: poetry run pytest
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry build
        poetry publish
